const express = require("express");
const GenericController = require("../controllers/generic.controller");
const router = express.Router();
const controller = new GenericController("serviceType");
router.get("/", controller.getAll);
router.get("/:id", controller.getById);
router.post("/", controller.create);
router.put("/:id", controller.update);
router.delete("/:id", controller.delete);
module.exports = router;
